### ISSUE TITLE
Can not delete a key after upgrading to version 1.0

### ISSUE THREAD

**Issue by mpPassendo** [aerospike/php-client#27] opened 2024-04-05 20:05 UTC
Hi,

I just updated from v0.4.0-alpha to version 1.0. I tried to run my previous test but I got an error "attempt to use an Enterprise feature on a Community server or a server without the applicable feature key". It turns out that that exception is thrown if I call delete method. I tried with examples you provided - and I can confirm it that it is not working and I am getting that error. I am using this image as server aerospike/aerospike-server:6.3.0.16_1. In the example you provided you are also using method close on client and that method is removed with latest update. 

I managed to make it work upgrading my docker setup - but I needed some time. It would be nice if you provide these instructions as well. 

Thanks,
Milan

**Comment by vmsachin** [comment] 2024-04-08 15:19
Hello,

Thank you for the feedback @mpPassendo . Just had a clarifying question - when you mention the upgrading the docker setup, what exactly was upgraded? It would help us review this in depth

Thank you!

**Comment by mpPassendo** [comment] 2024-04-08 15:46
Hi,

I mean upgrading my local development environment (upgraded to PHP 8.3 from 8.1 because v0.4.0-alpha supported this version). So I created new aerospike.so file for PHP 8.3 and I am running socket using aerospike-connection-manager whenever docker container is up (using entrypoint). Do you need more info?

Regards,
Milan

**Comment by vmsachin** [comment] 2024-04-08 17:37
Hi Milan,

Im trying to understand what caused the failure. Was it because you were using an older version of the Aerospike-connection-manager?

**Comment by mpPassendo** [comment] 2024-04-08 18:26
Hi,

Nope. Let me simplify it :) I completed all steps, I can see that Aerospike extension is loaded and that is working. I can set a  key but I can not delete it. When I tried to delete it - I got this message  "attempt to use an Enterprise feature on a Community server or a server without the applicable feature key". Before updating everything worked. Please let me know if you need more information.

Thanks
Milan

**Comment by vmsachin** [comment] 2024-04-08 18:37
Thank you for simplifying it :D. I am trying to replicate the issue but unable to do so. I am using php-client 1.0.0 and Aerospike server 6.3.0.6_1. Could you try to upgrade the server and see if you get the same issue.

**Comment by mpPassendo** [comment] 2024-04-08 20:47
Hi,
 
I upgraded Aerospike server to v7.0, php version 8.3.4 - but I got the same error unfortunately - "Aerospike\AerospikeException: attempt to use an Enterprise feature on a Community server or a server without the applicable feature key". All the other operations works perfectly.

**Comment by mpPassendo** [comment] 2024-04-09 11:53
Hi,

I tried to create simplified docker setup for php project & Aerospike - [](https://github.com/pssndo/astesting )

When I tried to run index.php I got the same message "Aerospike\AerospikeException: attempt to use an Enterprise feature on a Community server or a server without the applicable feature key". Set & get is working as expected.

Thanks
Milan

**Comment by vmsachin** [comment] 2024-04-09 16:13
@mpPassendo Thank you for the GitHub repo. I reproduced the issue. Seems like it happening with the community edition of Aerospike Server. We are looking why this is happening. Will update once it is fixed.
cc: @piyush-bansal1989 

Thanks!

**Comment by vmsachin** [comment] 2024-04-10 16:33
@mpPassendo @piyush-bansal1989 we have identified the issue, will release the fix in patch 1.0.1
will notify you on release

**Comment by vmsachin** [comment] 2024-04-16 18:31
@mpPassendo @piyush-bansal1989 This issue has been fixed with v1.0.1 release. Please let us know if you face any other issues.

**Closed by vmsachin** 2024-04-16 18:31 UTC
Labels: bug
